# Generated by Django 6.0.3 on 2026-03-11 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('radius', models.FloatField()),
                ('distance_from_sun', models.FloatField()),
                ('orbital_period', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
    ]
