# Generated by Django 6.0.3 on 2026-04-03 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='mass_earth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planet',
            name='temperature',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
